apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dmk-eksctl1
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.xlarge
    desiredCapacity: 2
    ssh:
      publicKeyPath: ~/keys/kube01.pem
