apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "*.amazonaws.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
          #- path: /(?!nginx-health)$
          #  backend:
          #    serviceName: dmk-ing-nginx-ingress
          #    servicePort: 80
