apiVersion: v1
kind: Namespace
metadata:
  name: my-spark-gcp
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-spark-gcp
spec:
  targetNamespaces:
  - my-spark-gcp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-spark-gcp
  namespace: my-spark-gcp
spec:
  channel: alpha
  name: spark-gcp
  source: operatorhubio-catalog
  sourceNamespace: olm